# Generated by Django 4.2.6 on 2023-10-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_country_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='state_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country_tb')),
            ],
        ),
    ]
